agents:
  - filename: generated/fetcher.py
    agent_name: fetcher
    description: "An agent that fetches information from the web."
    system_message: "You are a agent that fetches information off the web."
    test_message: "fetch information about the recent nepal incident."
    timeout: 45 
    tools:
      - name: fetch_server
        params:
          command: "npx"
          args: ["-y", "@brave/brave-search-mcp-server"]
          env:
            BRAVE_API_KEY: "${BRAVE_API_KEY}"
    output_to: summarizer
  - filename: generated/summarizer.py
    agent_name: summarizer
    description: "An agent that summarizes paragraphs into concise points."
    system_message: "You are a summarizer agent. Take long text and output concise summaries. You ouput only the summaries, no other text."
    timeout: 20 
    